### ISSUE TITLE
Server code?

### ISSUE THREAD

**Issue by brspurri** [humbertojaimes/DemoAzureOfflineSync#1]
Do you have server code to share for `http://mod5sample.azurewebsites.net/`? 
I'm trying to learn mobile sync, and your code is great for the client side, but I'm having trouble learning what the server side should be doing.

**Comment by humbertojaimes** [comment]
@brspurri actually there is no source code. Everything was creating using the Azure Portal, but the sample is really old so I think the best for you is look for a recent implementation.
